version: '3.8'

services:
  nestjt_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_DATABASE=blog-sql
      - APP_PORT=3000
    volumes:
      - ./src:/user/src/app/src
    depends_on:
      - mysql_db
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network


  mysql_db:
    image: mysql:8.0
    ports:
      - '3310:3306'  
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=blog-sql
    networks:
      - app-network

networks:
  app-network:
